//User Reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const  SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const SET_ADMIN = 'SET_ADMIN'
export const LOADING_USER = 'LOADING_USER'
export const LOGOUT = 'LOGOUT'

export const CHANGE_SIGN_OR_PHOTO = 'CHANGE_SIGN_OR_PHOTO'

//UI reducer types
export const  SET_ERRORS = 'SET_ERRORS'
export const  LOADING_UI = 'LOADING_UI'
export const  CLEAR_ERRORS = 'CLEAR_ERRORS'
export const  STOP_LOADING_UI = 'STOP_LOADING_UI'
export const SET_OPERATION_SUCCESS = 'SET_OPERATION_SUCCESS'

//Data reducer types
export const LOADING_DATA = 'LOADING_DATA'
export const SET_DATA_STUDENT = 'SET_DATA_STUDENT'
export const STOP_LOADING_DATA = "STOP_LOADING_DATA"
export const SET_INITIALVALUE = 'SET_INITIALVALUE'
export const SET_DATA_ADMIN= 'SET_DATA_ADMIN'
export const SET_GLOBAL_STUDENT_LOADING = 'SET_GLOBAL_STUDENT_LOADING'
export const SET_GLOBAL_ADMIN_LOADING = 'SET_GLOBAL_ADMIN_LOADING'
export const STOP_GLOBAL_STUDENT_LOADING = 'STOP_GLOBAL_STUDENT_LOADING'
export const STOP_GLOBAL_ADMIN_LOADING = 'STOP_GLOBAL_ADMIN_LOADING'
export const SET_ADMIN_ERROR = 'SET_ADMIN_ERROR'
export const SET_STUDENT_ERROR = 'SET_STUDENT_ERROR'

