export const STUDENT_FIELDS = [
  'enrollment',
  'first_name',
  'middle_name',
  'last_name',
  'email',
  'contact',
  'password',
  'confirm_password',
  'gender',
  'caste',
  'religion',
  'addmission_year',
  'admission_category',
  'semester',
  'branch',
  'course',
  'photo',
  'sign',
  'father_name',
  'mother_name',
  'aadhar',
  'voter_id',
  'date_of_birth',
  'blood_group',
  'thelasemia',
  're_add_l1',
  're_add_l2',
  're_add_city',
  're_add_state',
  're_add_pin_code',
  're_add_country',
  'pr_add_l1',
  'pr_add_l2',
  'pr_add_city',
  'pr_add_state',
  'pr_add_pin_code',
  'pr_add_country',
  'hsc_year',
  'hsc_pr',
  'ssc_year',
  'ssc_pr',
  'father_occupation',
  'off_add_l1',
  'off_add_l2',
  'off_add_city',
  'off_add_state',
  'off_add_pin_code',
  'off_add_country',
  'mother_occupation',
  'family_income',
];

export const ADMIN_FIELDS = [
  'faculty_id',
  'first_name',
  'middle_name',
  'last_name',
  'gender',
  'role',
  'designation',
  'branch',
  // "branch_year",
  'email',
  'contact',
  'password',
  'confirm_password',
  're_add_l1',
  're_add_l2',
  're_add_city',
  're_add_state',
  're_add_pin_code',
  're_add_country',
  'date_of_birth',
  'blood_group',
  'photo',
  'sign',
];

export const GENDER = { Male: 'male', Female: 'female', Other: 'other' };

export const CASTE = {
  OPEN: 'open',
  ST: 'st',
  SC: 'sc',
  OBC: 'obc',
  Other: 'other',
};

export const ADDMISSION_CATEGORIES = {

  TFWS: 'tfws',
  GENERAL: 'general',
  SEBC: 'sebc',
  ST: 'st',
  SC:'sc',
  TFW: 'tfw',
  EWS: 'ews',
  PH: 'ph',
  INTERNATIONAL: 'international',
  OTHER_STATE_OUTSIDE_OF_GUJARAT: 'other_state_outside_of_gujarat',
};

export const YEAR = {
  2021: 2021,
  2020: 2020,
  2019: 2019,
  2018: 2018,
  2017: 2017,
  2016: 2016,
  2015: 2015,
  2014: 2014,
  2013: 2013,
  2012: 2012,
};

export const SEMESTER = {
  '1st SEM': '1',
  '2nd SEM': '2',
  '3rd SEM': '3',
  '4th SEM': '4',
  '5th SEM': '5',
  '6th SEM': '6',
  '7th SEM': '7',
  '8th SEM': '8',
};

export const BRANCH_BE = {
  'Automobile Engineering': 2,
  'Biomedical Engineering': 3,
  'Chemical Engineering': 5,
  'Civil Engineering': 6,
  'Computer Engineering': 7,
  'Electrical Engineering': 9,
  'Electronics & Communication Engineering': 11,
  'Environment Engineering': 13,
  'Information Technology': 16,
  'Instrumentation & Control Engineering': 17,
  'Mechanical Engineering': 19,
  'Plastic Technology': 23,
  'Rubber Technology': 26,
  'Textile Technology': 29,
};

export const BRANCH_PDDC = {
  'Civil Engineering': 6,
  'Electrical Engineering': 9,
  'Electronics & Communication Engineering': 11,
  'Mechanical Engineering': 19,
};

//code of mca is not decided yet
export const BRANCH_MCA={
  'Master Of Computer Application' : 13,
}

export const BRANCH_PG = {
  'Applied Instrumentation': 3,
  'Communication Systems': 5,
  // "Computer Aided Design & Manufacturing": 1,
  'Computer Aided Process Design': 16,
  'Computer Science & Technology': 38,
  'Cryogenic Engineering': 10,
  'Electrical Engineering': 17,
  'Environmental Management': 18,
  'Geotechnical Engineering': 43,
  'Information Technology': 23,
  'Internal Combustion Engines & Automobile': 11,
  'Master of Computer Application': 93,
  'Rubber Technology': 40,
  'Structural Engineering': 20,
  // "Structural Engineering": 20,
  'Textile Engineering': 25,
  'Transportation Engineering': 13,
  'Water Resources & Management': 12,
};

export const COURSE = {
  BE: 'BE',
  PDDC: 'PDDC',
  PG: 'PG',
  MCA :'MCA'
};

export const BLOOD_GROOP = {
  'A+': 'A+',
  'A-': 'A-',
  'AB+': 'AB+',
  'AB-': 'AB-',
  'B+': 'B+',
  'B-': 'B-',
  'O+': 'O+',
  'O-': 'O-',
};

export const THELASEMIA = {
  Alpha: 'Alpha',
  Beta: 'Beta',
  Negative: 'Negative',
};

export const COUNTRY = {
  Afghanistan: 'AF',
  Albania: 'AL',
  Algeria: 'DZ',
  'American Samoa': 'AS',
  Andorra: 'AD',
  Angola: 'AO',
  Anguilla: 'AI',
  Antarctica: 'AQ',
  'Antigua and Barbuda': 'AG',
  Argentina: 'AR',
  Armenia: 'AM',
  Aruba: 'AW',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Bahamas: 'BS',
  Bahrain: 'BH',
  Bangladesh: 'BD',
  Barbados: 'BB',
  Belarus: 'BY',
  Belgium: 'BE',
  Belize: 'BZ',
  Benin: 'BJ',
  Bermuda: 'BM',
  Bhutan: 'BT',
  Bolivia: 'BO',
  'Bosnia and Herzegowina': 'BA',
  Botswana: 'BW',
  'Bouvet Island': 'BV',
  Brazil: 'BR',
  'British Indian Ocean Territory': 'IO',
  'Brunei Darussalam': 'BN',
  Bulgaria: 'BG',
  'Burkina Faso': 'BF',
  Burundi: 'BI',
  Cambodia: 'KH',
  Cameroon: 'CM',
  Canada: 'CA',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  'Central African Republic': 'CF',
  Chad: 'TD',
  Chile: 'CL',
  China: 'CN',
  'Christmas Island': 'CX',
  'Cocos (Keeling) Islands': 'CC',
  Colombia: 'CO',
  Comoros: 'KM',
  Congo: 'CG',
  'Congo, the Democratic Republic of the': 'CD',
  'Cook Islands': 'CK',
  'Costa Rica': 'CR',
  "Cote d'Ivoire": 'CI',
  'Croatia (Hrvatska)': 'HR',
  Cuba: 'CU',
  Cyprus: 'CY',
  'Czech Republic': 'CZ',
  Denmark: 'DK',
  Djibouti: 'DJ',
  Dominica: 'DM',
  'Dominican Republic': 'DO',
  'East Timor': 'TP',
  Ecuador: 'EC',
  Egypt: 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  Eritrea: 'ER',
  Estonia: 'EE',
  Ethiopia: 'ET',
  'Falkland Islands (Malvinas)': 'FK',
  'Faroe Islands': 'FO',
  Fiji: 'FJ',
  Finland: 'FI',
  France: 'FR',
  'France, Metropolitan': 'FX',
  'French Guiana': 'GF',
  'French Polynesia': 'PF',
  'French Southern Territories': 'TF',
  Gabon: 'GA',
  Gambia: 'GM',
  Georgia: 'GE',
  Germany: 'DE',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greece: 'GR',
  Greenland: 'GL',
  Grenada: 'GD',
  Guadeloupe: 'GP',
  Guam: 'GU',
  Guatemala: 'GT',
  Guinea: 'GN',
  'Guinea-Bissau': 'GW',
  Guyana: 'GY',
  Haiti: 'HT',
  'Heard and Mc Donald Islands': 'HM',
  'Holy See (Vatican City State)': 'VA',
  Honduras: 'HN',
  'Hong Kong': 'HK',
  Hungary: 'HU',
  Iceland: 'IS',
  India: 'IN',
  Indonesia: 'ID',
  'Iran (Islamic Republic of)': 'IR',
  Iraq: 'IQ',
  Ireland: 'IE',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Japan: 'JP',
  Jordan: 'JO',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kiribati: 'KI',
  "Korea, Democratic People's Republic of": 'KP',
  'Korea, Republic of': 'KR',
  Kuwait: 'KW',
  Kyrgyzstan: 'KG',
  "Lao People's Democratic Republic": 'LA',
  Latvia: 'LV',
  Lebanon: 'LB',
  Lesotho: 'LS',
  Liberia: 'LR',
  'Libyan Arab Jamahiriya': 'LY',
  Liechtenstein: 'LI',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Macau: 'MO',
  'Macedonia, The Former Yugoslav Republic of': 'MK',
  Madagascar: 'MG',
  Malawi: 'MW',
  Malaysia: 'MY',
  Maldives: 'MV',
  Mali: 'ML',
  Malta: 'MT',
  'Marshall Islands': 'MH',
  Martinique: 'MQ',
  Mauritania: 'MR',
  Mauritius: 'MU',
  Mayotte: 'YT',
  Mexico: 'MX',
  'Micronesia, Federated States of': 'FM',
  'Moldova, Republic of': 'MD',
  Monaco: 'MC',
  Mongolia: 'MN',
  Montserrat: 'MS',
  Morocco: 'MA',
  Mozambique: 'MZ',
  Myanmar: 'MM',
  Namibia: 'NA',
  Nauru: 'NR',
  Nepal: 'NP',
  Netherlands: 'NL',
  'Netherlands Antilles': 'AN',
  'New Caledonia': 'NC',
  'New Zealand': 'NZ',
  Nicaragua: 'NI',
  Niger: 'NE',
  Nigeria: 'NG',
  Niue: 'NU',
  'Norfolk Island': 'NF',
  'Northern Mariana Islands': 'MP',
  Norway: 'NO',
  Oman: 'OM',
  Pakistan: 'PK',
  Palau: 'PW',
  Panama: 'PA',
  'Papua New Guinea': 'PG',
  Paraguay: 'PY',
  Peru: 'PE',
  Philippines: 'PH',
  Pitcairn: 'PN',
  Poland: 'PL',
  Portugal: 'PT',
  'Puerto Rico': 'PR',
  Qatar: 'QA',
  Reunion: 'RE',
  Romania: 'RO',
  'Russian Federation': 'RU',
  Rwanda: 'RW',
  'Saint Kitts and Nevis': 'KN',
  'Saint LUCIA': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  Samoa: 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  Senegal: 'SN',
  Seychelles: 'SC',
  'Sierra Leone': 'SL',
  Singapore: 'SG',
  'Slovakia (Slovak Republic)': 'SK',
  Slovenia: 'SI',
  'Solomon Islands': 'SB',
  Somalia: 'SO',
  'South Africa': 'ZA',
  'South Georgia and the South Sandwich Islands': 'GS',
  Spain: 'ES',
  'Sri Lanka': 'LK',
  'St. Helena': 'SH',
  'St. Pierre and Miquelon': 'PM',
  Sudan: 'SD',
  Suriname: 'SR',
  'Svalbard and Jan Mayen Islands': 'SJ',
  Swaziland: 'SZ',
  Sweden: 'SE',
  Switzerland: 'CH',
  'Syrian Arab Republic': 'SY',
  'Taiwan, Province of China': 'TW',
  Tajikistan: 'TJ',
  'Tanzania, United Republic of': 'TZ',
  Thailand: 'TH',
  Togo: 'TG',
  Tokelau: 'TK',
  Tonga: 'TO',
  'Trinidad and Tobago': 'TT',
  Tunisia: 'TN',
  Turkey: 'TR',
  Turkmenistan: 'TM',
  'Turks and Caicos Islands': 'TC',
  Tuvalu: 'TV',
  Uganda: 'UG',
  Ukraine: 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'United States Minor Outlying Islands': 'UM',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  Vanuatu: 'VU',
  Venezuela: 'VE',
  'Viet Nam': 'VN',
  'Virgin Islands (British)': 'VG',
  'Virgin Islands (U.S.)': 'VI',
  'Wallis and Futuna Islands': 'WF',
  'Western Sahara': 'EH',
  Yemen: 'YE',
  Yugoslavia: 'YU',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
};

export const ADMIN_ROLE = {
  'Department Mentor': 'ROLE_DEPARTMENT',
  'SS Mentor': 'ROLE_SSMENTOR',
  'SS Head': 'ROLE_SSHEAD',
};

export const BRANCH_YEAR = {
  '1st Year': 1,
  '2nd Year': 2,
  '3rd Year': 3,
  '4th Year': 4,
};
export const FEETYPE = {
  'Exam Fee': 'GTU',
  'College Fee': 'COLLEGE',
};

export const getBranch = (branchCode, course) => {
  if (!branchCode || !course) return;
  let BRANCH;
  switch (course) {
    case 'BE':
      BRANCH = BRANCH_BE;
      break;
    case 'PDDC':
      BRANCH = BRANCH_PDDC;
      break;
    case 'PG':
      BRANCH = BRANCH_PG;
      break;
    default:
      return;
  }
  for (var prop in BRANCH) {
    if (BRANCH[prop] == branchCode) return prop;
  }
};
